# Generated by Django 5.0.4 on 2024-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user_rating',
            field=models.CharField(max_length=255),
        ),
    ]
